name: API client publish to Reposilite

on:
  push:
    branches: [ main, dev, qa, release ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./client/gradlew.bat
      - name: Publish to Reposilite
        run: ./client/gradlew.bat publish